### ISSUE TITLE
Replace CURL with DokuWiki's HTTP client

### ISSUE THREAD

**Issue by splitbrain** [meteotest/jiralinks#13]
Just a suggestion: instead of relying on CURL use the HTTPClient bundled with DokuWiki: https://www.dokuwiki.org/devel:httpclient

**Comment by cstuder** [comment]
Oh, thanks for the hint. I will refactor that.

**Comment by cstuder** [comment]
Hmm, I don't think that it is poosible to use the HTTPClient: I need to post raw JSON strings to the Jira API, the post()-function doesn't allow that. (If I pass the data as string, it assumes form encoded values: http://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/HTTPClient.php.source.html#l287)
